baseURL: https://atobaum.github.io/wiki
languageCode: ko-KR
title: Atobaum Wiki
defaultContentLanguage: ko
enableEmogi: false
enableGitInfo: false
enableInlineShortcodes: false
googleAnalytics: ""
hasCJKLanguage: true

frontmatter:
    date: [":fileModTime", ":git", "lastmod", "date"]

menu:
    main:
        - name: all
          url: /
        - name: tags
          url: /tags
        - name: random
          url: /random
        - name: about   
          url: /about
params:
    DateFormat: "2006-01-01"
