baseURL: https://atobaum.github.io/wiki
languageCode: ko-KR
title: Atobaum Wiki
defaultContentLanguage: ko
enableEmogi: false
enableGitInfo: false
enableInlineShortcodes: false
googleAnalytics: ""
hasCJKLanguage: true

frontmatter:
    date: ["date", ":git", "lastmod", ":fileModTime"]
    publishDate: [":default", ":fileModTime"]
    lastmod: [":default", ":fileModTime"]

menu:
    main:
        - name: all
          url: /
        - name: tags
          url: /tags
        - name: random
          url: /random
        - name: about   
          url: /about
params:
    DateFormat: "2006-01-01"
    Social:
        - github: atobaum
